package net.uncorp.blinkr

/** Generated by scripts/gen-site-icons.py. Each site's logo (res/drawable/site_<id>.xml). */
object SiteIcons {
    val BY_ID: Map<String, Int> = mapOf(
        "bereal" to R.drawable.site_bereal,
        "bluesky" to R.drawable.site_bluesky,
        "discord" to R.drawable.site_discord,
        "facebook" to R.drawable.site_facebook,
        "instagram" to R.drawable.site_instagram,
        "linkedin" to R.drawable.site_linkedin,
        "messenger" to R.drawable.site_messenger,
        "pinterest" to R.drawable.site_pinterest,
        "quora" to R.drawable.site_quora,
        "reddit" to R.drawable.site_reddit,
        "snapchat" to R.drawable.site_snapchat,
        "telegram" to R.drawable.site_telegram,
        "threads" to R.drawable.site_threads,
        "tiktok" to R.drawable.site_tiktok,
        "truthsocial" to R.drawable.site_truthsocial,
        "tumblr" to R.drawable.site_tumblr,
        "twitch" to R.drawable.site_twitch,
        "vk" to R.drawable.site_vk,
        "x" to R.drawable.site_x,
        "youtube" to R.drawable.site_youtube,
    )

    /** Logos that are plain black: drawn in the text colour instead, so they stay visible in dark mode. */
    val INK: Set<String> = setOf("bereal", "snapchat", "threads", "tiktok", "x")
}
