#!/usr/bin/env python3
"""Site logos: download them from Simple Icons (CC0) into art/sites/, then write one vector
drawable per site (res/drawable/site_<id>.xml) in the brand colour.

Sites missing from Simple Icons have a hand-made SVG in art/sites/ and a colour in MANUAL.

usage: scripts/gen-site-icons.py
"""
import json
import os
import re
import urllib.request

VERSION = "16.34.0"
CDN = f"https://cdn.jsdelivr.net/npm/simple-icons@{VERSION}"

# site id (Sites.kt) -> Simple Icons slug
SLUGS = {
    "bereal": "bereal", "bluesky": "bluesky", "discord": "discord",
    "facebook": "facebook", "instagram": "instagram",
    "messenger": "messenger",
    "pinterest": "pinterest", "quora": "quora", "reddit": "reddit",
    "snapchat": "snapchat", "telegram": "telegram",
    "threads": "threads", "tiktok": "tiktok", "tumblr": "tumblr", "twitch": "twitch", "x": "x",
    "vk": "vk", "youtube": "youtube",
}
# Not in Simple Icons (LinkedIn was removed at its request): art/sites/<id>.svg is drawn by hand; brand colour here
MANUAL = {"truthsocial": "5448EE", "linkedin": "0A66C2"}
# Brand colours too light to read on white get this instead
LIGHT = {"FFFC00": "000000"}  # Snapchat yellow -> black

root = os.path.join(os.path.dirname(__file__), "..")
art = os.path.join(root, "art/sites")
res = os.path.join(root, "app/src/main/res/drawable")
os.makedirs(art, exist_ok=True)


def slugify(title):
    return re.sub(r"[^a-z0-9]", "", title.lower())


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read().decode()


NUM = re.compile(r"[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?")


def normalise(d):
    """Rewrite path data with every number separated. Android's parser misreads packed arc flags
    such as "a19.8 19.8 0 00-4.9", which SVG allows (flags are single 0/1 digits)."""
    out, i, cmd, n = [], 0, "", 0
    while i < len(d):
        c = d[i]
        if c.isalpha():
            cmd, n = c, 0
            out.append(c)
            i += 1
        elif c in " ,\t\n":
            i += 1
        elif cmd in "aA" and n % 7 in (3, 4):  # large-arc and sweep flags: one digit each
            out.append(c)
            n += 1
            i += 1
        else:
            m = NUM.match(d, i)
            out.append(m.group())
            n += 1
            i = m.end()
    return " ".join(out)


colours = {}
need = [s for i, s in SLUGS.items() if not os.path.exists(os.path.join(art, f"{i}.svg"))]
data = json.loads(fetch(f"{CDN}/data/simple-icons.json"))
for icon in data:
    slug = icon.get("slug") or slugify(icon["title"])
    colours[slug] = icon["hex"].upper()

for site, slug in SLUGS.items():
    path = os.path.join(art, f"{site}.svg")
    if not os.path.exists(path):
        open(path, "w").write(fetch(f"{CDN}/icons/{slug}.svg"))

ink = []
for site in list(SLUGS) + list(MANUAL):
    svg = open(os.path.join(art, f"{site}.svg")).read()
    d = normalise(" ".join(re.findall(r'<path[^>]* d="([^"]+)"', svg)))
    colour = MANUAL.get(site) or colours[SLUGS[site]]
    colour = LIGHT.get(colour, colour)
    if colour == "000000":
        ink.append(site)
    open(os.path.join(res, f"site_{site}.xml"), "w").write(f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated from art/sites/{site}.svg by scripts/gen-site-icons.py. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path android:fillColor="#FF{colour}" android:pathData="{d}" />
</vector>
""")
    print(site, colour)

# SiteIcons.kt: id -> drawable, and the black logos (drawn in the text colour, so they show in dark mode)
ids = sorted(list(SLUGS) + list(MANUAL))
entries = "\n".join(f'        "{i}" to R.drawable.site_{i},' for i in ids)
inks = ", ".join(f'"{i}"' for i in sorted(ink))
open(os.path.join(root, "app/src/main/java/net/uncorp/blinkr/SiteIcons.kt"), "w").write(f'''package net.uncorp.blinkr

/** Generated by scripts/gen-site-icons.py. Each site's logo (res/drawable/site_<id>.xml). */
object SiteIcons {{
    val BY_ID: Map<String, Int> = mapOf(
{entries}
    )

    /** Logos that are plain black: drawn in the text colour instead, so they stay visible in dark mode. */
    val INK: Set<String> = setOf({inks})
}}
''')
